name: Clean up
on:
  #schedule:
  #  - cron: '0 12 * * FRI'  # Every Fridat at midnight
  workflow_dispatch:
jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - name: Clean Pandas translation repository
        uses: Scientific-Python-Translations/clean-up@main
        with:
          translations-repo: "Scientific-Python-Translations/pandas-translations"
          translations-ref: "main"
          # These are provided by the Scientific Python Project and allow
          # automation with bots
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          token: ${{ secrets.TOKEN }}
